<?php
if(!defined(WP_UNINSTALL_PLUGIN)) {exit()};

// delete options
        delete_option('qpwpfn1');
        delete_option('qpwpfn2');
        delete_option('qpwpfn3');
        delete_option('qpwpfn4');
        delete_option('qpwpfn5');
        delete_option('qpwpfn6');
        delete_option('qpwpfn7');
        delete_option('qpwpfn8');
        delete_option('qpwpfn9');
        delete_option('qpwpfn10');
        delete_option('qpwpfn11');
        delete_option('qpwpfn12');
        delete_option('qpwpfn13');
        delete_option('qpwpfn14');
        delete_option('qpwpfn15');
        delete_option('qpwpfn16');
        delete_option('qpwpfn17');
        delete_option('qpwpfn18');
        delete_option('qpwpfn19');
        delete_option('qpwpfn20');
        delete_option('qpwpfn21');
        delete_option('qpwpfn22');
        delete_option('qpwpfn_as');
        delete_option('qpwpfn_bf');
        delete_option('qpwpfn_cdcon');
        delete_option('qpwpfn_cdtit');
        delete_option('qpwpfn_cl');
        delete_option('qpwpfn_ch');
        delete_option('qpwpfn_furl1');
        delete_option('qpwpfn_furl2');
        delete_option('qpwpfn_ga');
        delete_option('qpwpfn_grbn');
        delete_option('qpwpfn_grim');
        delete_option('qpwpfn_lge');
        delete_option('qpwpfn_jq');
?>